/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Auth: () => import('#controllers/auth/auth_controller'),
  },
  Example: () => import('#controllers/example_controller'),
}
